baseurl = "joelaul.dev"
title = "Joe Lauletta"
theme = "nix"
languageCode = "en-us"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "portfolio"
    weight = 1
    url = "portfolio"

[params]
  Name = "Joe Lauletta"
  GithubID = "joelaul"
  LinkedInID = "joe-lauletta-271508132/"
  InstagramID = "joelaul"
  SpotifyID = "d"
  Email = "laulettaj@gmail.com"

  HeaderUsername = "joe"
  HeaderHostname = "joelaul.dev"

  About = "ğŸ¸ğŸ‘¨â€ğŸ’» I'm a guitarist and recording artist turned fullstack developer. I like building things that awaken people's curiosity."

  ProfilePicture = "/profile.png"
  Favicon = "/favicon.ico/"

