baseurl = "https://joelaul.dev/"
title = "Joe Lauletta"
theme = "nix"
languageCode = "en-us"

[menu]
  [[menu.header]]
    name = "projects"
    weight = 1
    url = "projects"
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"

[params]
  Name = "Joe Lauletta"
  GithubID = "joelaul"
  LinkedInID = "joe-lauletta"
  InstagramID = "joelaul"
  Email = "laulettaj@gmail.com"

  HeaderUsername = "you"
  HeaderHostname = "joelaul.dev"

  About = "ğŸ¸ğŸ‘¨â€ğŸ’» I'm a guitarist and recording artist turned fullstack developer. I like building things that awaken people's curiosity."

  ProfilePicture = "/profile.png"
  Favicon = "favicon.ico"