baseurl = "https://joelaul.dev/"
title = "Joe Lauletta | Software Engineer"
theme = "nix"
languageCode = "en-us"
pluralizelisttitles = false

[taxonomies]
  tag = 'tags'

[menu]
  [[menu.header]]
    name = "portfolio"
    weight = 1
    url = "/portfolio"
  [[menu.header]]
    name = "blog"
    weight = 2
    url = "/blog"

[params]
  Favicon = "favicon.ico"

  HeaderUsername = "you"
  HeaderHostname = "joelaul.dev"

  ProfilePicture = "/profile-bw.png"

  Name = "Joe Lauletta"
  GithubID = "joelaul"
  LinkedInID = "joelaul"
  InstagramID = "joelaul"
  SpotifyID = "joelaul"
  Resume = " "

  About = "ğŸ¸ğŸ‘¨â€ğŸ’» I'm a guitarist and recording artist turned fullstack developer. I like building things that awaken people's curiosity."